version: '2'

services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  homeassistant:
    container_name: home-assistant
    image: homeassistant/armhf-homeassistant
    volumes:
      - /opt/has/config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      #- /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
    network_mode: host
  mqtt:
    container_name: mqtt
    image: rufik/docker-mosquitto-armhf
    volumes:
      - /opt/mqtt/config:/mqtt/config:ro
      - /opt/mqtt/data/:/mqtt/data/
      - /opt/mqtt/log:/mqtt/log
    restart: always
    network_mode: host

volumes:
  portainer_data:
