homeassistant:
  name: Home
  latitude: 51.0
  longitude: 19.0
  elevation: 200
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  include_used_components: true

# Discover some devices automatically
discovery:

mqtt:
  broker: localhost
  port: 1883

recorder:
  #keep only last month in SQL, whole data goes into influxdb
  purge_keep_days: 30
  db_url: mysql://user:pwd@localhost:3307/HASS?charset=utf8
  purge_interval: 1

influxdb:
  host: localhost
  port: 8086
#  username: user
#  password: password
  database: HASS

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:

# Text to speech
tts:
#  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
